name: Python CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install
        run: pip install pytest flake8 pylint

      - name: Lint flake8
        run: flake8 . || true

      - name: Lint pylint
        run: pylint main.py || true

      - name: Run tests
        run: pytest || true
